sudo: required

services:
  - docker

before_install:
  - docker build --pull=true --rm=true -t patrickdappollonio/alpine-packer .

script:
  - docker run --rm -it patrickdappollonio/alpine-packer /bin/ash -c "echo 'Hello'"

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push patrickdappollonio/alpine-packer;
    fi
